### ISSUE TITLE
スケジュールページへのリンクをツイートに追加

### ISSUE THREAD

**Issue by ymyzk** [camphor-/schedule-notifier#2]
スケジュールページへのリンクをツイートに追加しておくと, ツイートから簡単に開館予定にアクセスできて便利そう.

**Comment by ymyzk** [comment]
https://camph.net/schedule/ が Twitter できれいに見えるように Card を設定しておいた方が良い.

**Comment by p1ass** [comment]
これ便利そう

**Comment by KMConner** [comment]
Done in #28
