### ISSUE TITLE
Make 用に通知機能を修正する

### ISSUE THREAD

**Issue by KMConner** [camphor-/schedule-notifier#31]
## 概要

hanreki 側の修正

- https://github.com/camphor-/hanreki/issues/31
- https://github.com/camphor-/hanreki/pull/35

に合わせて ツイートする際のメッセージを一部変更したい

### 当日の開館、イベントに関するツイート

Make の利用可能な時間帯をツイート内に含めるために以下のように修正したい。

それぞれの日に関して、 open と make の関係は以下のいずれかになるはず

1. 同じ日に Open と Make のイベントがあり、開始、終了時刻が同一の時
2. 同じ日に Open と Make のイベントがあり、開始、終了時刻の少なくとも片方が異なっているとき
3. ある日に Make のイベントはあるが Open のイベントはない場合
4. ある日に Open のイベントはあるが Make はない場合
5. Open も Make も存在しない日

その中で、

- 1 の場合には 今までのメッセージの最後に "CAMPHOR- Make" も使えますみたいな文言を追加したい
- 2 の場合には、開館時間を表すメッセージの後に、 Make イベントの開始、終了時刻を元に "Make は hh:mm ～ hh:mm に利用できます" と付け加えたい。 (Make の時間帯が Open の時間帯の subset になっていない場合はここでは考慮しない)
- 3 の場合には、同じ開始、終了時刻を持った Open のイベントがあるものとして 1 の場合と同じ動作  
  (つまり、開館時刻のメッセージの後に "Make も使えます" みたいなメッセージを付け加える)
- 4 の場合には今まで通り開館時刻をツイートする (今までの仕様通り)
- 5 の場合は何もしない (これも今までの仕様通り)

※ "Open" "Make" 以外のイベント名の扱いに関しては今まで通りで変更しない

### その週の開館、イベントに関するツイート

イベントに関するツイートは今までの仕様通り (ただし、 Make はイベントを宣伝するツイートに含まれてはいけないことに注意)

開館日に関しては、その日に Make が使える日に関して "(Make)" を開館時刻の後に付けたい。
それと、 Make とついてる日は CAMPHOR- Make が使えることを明記したい。

つまり、以下のツイートは 3/15 は Make が使えないが、 3/17 と 3/20 は Make が使えるという意味になる。
(Make と Open の開始、終了時刻が同一でも、違っても、その点は考慮しない)

> 今週の開館日です！
> 03/15 (月) 17:00〜19:00
> 03/17 (水) 16:00〜19:00 (Make)
> 03/20 (土) 16:00〜19:00 (Make)
>
> Make と書かれている日は CAMPHOR- Make が利用可能です。
> みなさんのお越しをお待ちしています!!
>
> その他の開館日はこちら

**Comment by 5ebec** [comment]
#33 で修正した

dry run結果
![](https://user-images.githubusercontent.com/38322494/128604319-690dbd55-628d-43cf-bbbf-70072a187d5f.png)

**Comment by 5ebec** [comment]
docker image を Registryのほうに移行した

**Comment by 5ebec** [comment]
明日10時から動くはずなので close
